### ISSUE TITLE
Getting midterm experiments

### ISSUE THREAD

**Issue by shuetrim** [McKibbin-Software-Group/issues#13]
From Karma:

I would like to seek some clarifications regarding accessing the data for the mid semester paper and also regarding the dataset that was used for today's tutorial.

Mid semester paper:
I have followed the steps provided by Geoff in updating the data for the mid-semester paper, however, I could not access it as I am sure I am missing out on something. I created a fork, however, I cannot find the "update branch" icon under sync fork. I have attached a screenshot of the issue.

Today's Tutorial:
Will the data that was used for today's tutorial be automatically available on our GitHub, as I can only see and have the old dataset (reimagined carnival) that was used for the previous classes? I have attached a screen shot of the available data currently on my GitHub.

Please let me know if I am missing out on something.

![image](https://github.com/user-attachments/assets/714732ca-0489-4842-9a9f-af909a74c429)

**Comment by shuetrim** [comment]
The screenshot suggests that your fork was created after the most recent changes to the original repository. There is no need to do a sync operation.

Your codespace is "reimagined carnival". Start that codespace and then, at the terminal, run the command 

```bash
git pull origin main
```

If that does not pull down the new experiment scripts, let me know by responding here and we can do a zoom to sort your issues.

Regards

Geoff

**Comment by Mpee1987** [comment]
Thank you Geoff.

**Comment by Mpee1987** [comment]
Hi Geoff,

When i run the command "git pull origin main" in the terminal, the new experiment scripts do not seem to be appearing. I have attached a screen shot of what I am actually receiving. 

Regards,
Karma
![Screenshot (105)](https://github.com/user-attachments/assets/91443406-989f-4e95-af96-e1fc987a58e5)

**Comment by shuetrim** [comment]
What is happening is that you have made some changes to files that would be overwritten if we pulled down the updates.

Here are a couple of git commands to run. These will create a new branch where your changes can be safely stored before going back to the main branch and pulling down the changes.

# Step 1 Create a new branch in the codespace.

At the terminal run:

```bash
git checkout -b mychanges
```

This will create a new branch called mychanges and switch across to that branch.

# Step 2 Stage all of your changes ready to be saved in the new branch.

```bash
git add .
```

# Step 3 Save your staged changes ready to be saved in the new branch

```bash
git commit -m "Saving my previous changes before downloading updates for midterm essay"
```
# Step 4 Return to the main branch

```bash
git checkout main
```

Your changes will no longer be in the codespace main branch because you stored them in the newly created branch above. There will no longer be conflicts.

# Step 5 pull down the updates

```bash
git pull origin main
```

Let me know if problems arise.

It does get more complex when you want to integrate the updates with your own changes.  I do not think it is necessary but if you want to do that, let me know. It would involve resolving conflicts between the two sources of changes.

Geoff
