### ISSUE TITLE
Can't get G-CUBED to install

### ISSUE THREAD

**Issue by cbrukner** [McKibbin-Software-Group/issues#4]
I've managed to get python and pip installed on my PC, and verify that they're installed. 

I replicated the instructions provided in Friday's tutorial to install the G-CUBED package, and this is what happens: 

![image](https://github.com/McKibbin-Software-Group/issues/assets/141594278/439e56cd-5fbc-4057-978e-d2e31d54fa90)

I've tried looking further at the installation instructions in the documentation. The relevant sections says: 

"To install the downloaded gcubed Python package, run the following command in your terminal from within the directory that contains the downloaded file:

pip install gcubed-1.0.3-py3-none-any.whl"

I thought that this is exactly what I've done. 

NB - I'm coming to this course with zero programming experience in any language. Apologies if the solution is obvious, and further apologies if I don't initially understand the responses and have to ask again!

**Comment by shuetrim** [comment]
Hi Charles

It is not obvious. 

It is interesting that you could successfully run 

```
py -m pip --version
```

but the pip command itself is not recognised.

I think you may have pip installed with one version of python that is invoked using `py` but another default Python interpreter is invoked with `python` and that version of python does not have the pip package installed. When you run

```
pip install gcubed-1.0.3-py3-none-any.whl
```

the default python reports that there is no pip package installed.

To test this idea, can you report the information you get when you run:

```
py --version
```

and 

```
python --version
```

It would also be good to see the output from when you ran:

py get-pip.py

Lastly, it is a bandaid solution, but you could try running:

```
py -m pip install gcubed-1.0.3-py3-none-any.whl
```

That may well get the package installed for use with the Python interpreter that is invoked with the command `py`.

Regards

Geoff

**Comment by cbrukner** [comment]
Hi Geoff, 

Thanks for the quick reply. 

Here's the output from the commands that you requested that I run:

![image](https://github.com/McKibbin-Software-Group/issues/assets/141594278/fcf2687c-da7c-4e2a-9d03-c70486b6939b)

It appears that this installation worked, although I don't really understand why. I got these warning messages toward the end, I don't know if they're important:
 
![image](https://github.com/McKibbin-Software-Group/issues/assets/141594278/341a833b-b762-4c1a-b596-2302dcb72514)

Also, do you have any resources for people like me with no programming experience - something that can get us across some programming/python basics in a manner that's relevant? The Crawford school's default/mandatory masters-level macro course is all done on pen and paper, so I suspect that there might be others who are a bit light on in this area too...

**Comment by cbrukner** [comment]
Thanks Geoff. 

I uninstalled Python and started again from scratch, and now things seems to be working better: 

![image](https://github.com/McKibbin-Software-Group/issues/assets/141594278/eb00e94d-5752-436f-b9c3-67144ad8be88)

I'll take a look at those resources.

**Comment by shuetrim** [comment]
Nice work. That does look better.

Regards

Geoff
