### ISSUE TITLE
issue with python installation

### ISSUE THREAD

**Issue by nkuk1** [McKibbin-Software-Group/issues#6]
Hi Geoff
I am getting an error while installing g-cubed v1.03

ERROR: Package 'gcubed' requires a different Python: 3.9.13 not in '>=3.10'

I have anaconda installed and looks like its got an older version of python, when i check pip version i get the following response

(base) Niteshs-MacBook-Pro:Downloads Nitesh$ pip --version
pip 23.2.1 from /opt/anaconda3/lib/python3.9/site-packages/pip (python 3.9)

What is the best way to get around this? 

Nitesh.

**Comment by shuetrim** [comment]
Hi Nitesh,

The issue is that you are running a version of python that was released before Python 3.10. Specifically, the error message indicates you are running python 3.9 (3.9.13 to be precise).

Install Python 3.11 and remove Python 3.9 and you should be back on track.

Regards

Geoff

**Comment by nkuk1** [comment]
Hi Geoff 

I have tried to do this without much success. I still get the same error even though i have removed anaconda completely from the system. 

On checking python versions i can only see Python 3.9.17 and the 3.11 installed prior doesnt even appear in the list. 

how do i go about completely removing Python 3.9?

**Comment by shuetrim** [comment]
If you are on Windows, use the [app uninstaller](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98).

**Comment by nkuk1** [comment]
Unfortunately i'm on a mac system.

**Comment by shuetrim** [comment]
Ahh - of course. I should have noticed in the error message you showed.

I do not have conda installed to test this but, to install an updated python try following the information at
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html

Succinctly:

`conda search python`

then 

`install conda python=3.11.?` replacing ? with the relevant value is in the search results.

That should migrate you to using that version of python.

Let me know how you get on.

Geoff

To remove old python versions

**Comment by nkuk1** [comment]
Thanks Geoff. This worked. That was slightly stressful 😅

By the way, what is conda and where does this fit into the python ecosystem?

and

Will there be any clashes if i have anaconda setup from hereon? i need it
for another course.

Regards
Nitesh.

**Comment by shuetrim** [comment]
conda/anaconda is helpful in enabling you to run different python setups on
the one computer.

I expect you will be fine with the other course but do let me know if they
are wanting you to use a version of python older than 3.10. That is
manageable with anaconda installed but you do need to look at the anaconda
documentation.

Regards

Geoff
