### ISSUE TITLE
Save command in Python

### ISSUE THREAD

**Issue by huyennguyen-anu** [McKibbin-Software-Group/issues#7]
Hi Jeff,

Do you know how to save the command after we finish our work with python?

Also, I cannot run the command "ls" and I tried to change to "dir". I see it displayed the same table of result but I'm not sure is there any differences between these 2 commands?

**Comment by shuetrim** [comment]
For your first question, I am not sure what you want to preserve. If it is the projections themselves or deviations between them, that should be done by the python program you run.

For the second question, ls and dir are very similar. dir comes from the windows dos operating system and ls comes from unix. Powershell allows for both on windows. Mac requires use of ls. the windows command prompt application requires dir.

Regards

Geoff
