### ISSUE TITLE
Could not find the sym_input_file

### ISSUE THREAD

**Issue by huyennguyen-anu** [McKibbin-Software-Group/issues#8]
Hi Geoff,

I am trying to run the simulation through Visual Studio Code but I receive the notice "Could not find the sym_input_file"
![Screenshot 2023-09-07 135333](https://github.com/McKibbin-Software-Group/issues/assets/141608215/509458ac-22f9-4897-9816-1d7f615c34d1)
Can you please let me know how to solve this issues?
Many thanks in advance!

**Comment by shuetrim** [comment]
Does the required file exist at the location? It should be at:

```
C:\Users\nhatm\model_2R_170logv7\sym\ggg2r170logv7.sym
```

This is one of the many files in the sym directory of the model you will have downloaded.

**Comment by huyennguyen-anu** [comment]
Yes, it cannot go to the right file directory although I downloaded the file model_2R_170logv7 and ggg2r170logv7 is already included on that file. I've sorted it out.

Thank you so much!

**Comment by shuetrim** [comment]
Glad it is resolved. Nice work!
