### ISSUE TITLE
G-Cubed Python

### ISSUE THREAD

**Issue by breussf** [McKibbin-Software-Group/issues#9]
Where can one find the shock inputs for the teaching examples in G-Cubed Pyhton?
Thanks,
Fritz

**Comment by shuetrim** [comment]
In the subdirectories of the ‘simulations’ directory.

**Comment by breussf** [comment]
Dear Geoff,

thank you for your answer to my “shock” question.

It would be nice to know how to make a standard simulations, like a shock to fiscal expenditure in the USA. Is there a guide how to execute this experiment?

Thank you and best regards,
Fritz

Von: Geoff Shuetrim ***@***.***>
Gesendet: Sonntag, 10. September 2023 23:29
An: McKibbin-Software-Group/issues ***@***.***>
Cc: Breuss, Fritz ***@***.***>; Author ***@***.***>
Betreff: Re: [McKibbin-Software-Group/issues] G-Cubed Python (Issue #9)

In the subdirectories of the ‘simulations’ directory.

**Comment by shuetrim** [comment]
From a technical perspective, read:

https://documentation.gcubed.com/simulations/

For the specifics of simulation design and which exogenous variables to shock, that is a question best directed to those delivering the course.

**Comment by breussf** [comment]
Dear Geoff,

thank you for the quick answer.

Best regards,
Fritz

Von: Geoff Shuetrim ***@***.***>
Gesendet: Montag, 11. September 2023 13:23
An: McKibbin-Software-Group/issues ***@***.***>
Cc: Breuss, Fritz ***@***.***>; Author ***@***.***>
Betreff: Re: [McKibbin-Software-Group/issues] G-Cubed Python (Issue #9)


From a technical perspective, read:

https://documentation.gcubed.com/simulations/

For the specifics of simulation design and which exogenous variables to shock, that is a question best directed to those delivering the course.

**Comment by shuetrim** [comment]
Hi Fritz,

My apologies for the slow response. Your questions led me to think you were doing the masters course at the Crawford School taught by Warwick McKibbin. If you are not doing that course, I would be happy to assist you with exploring how to use the teaching model to do various simulations.

If you want access to the full model, then you should reach out to Warwick at McKibbin Software Group. Warwick can be reached at mckibbinsoftwaregroup@gmail.com. More details are available at https://www.sensiblepolicy.com/

Regards

Geoff Shuetrim

**Comment by breussf** [comment]
Dear Geoff,

thank you very much for your information. Well, I am an Austrian economist interested in modeling for a long time. I know Warwick McKibbin from his visit and keynote lecture at the annual conference of the Austrian Economic Association.

So, before I dig deeper into the full model, I would be happy, if you could give me some advice, how to make standard simulations with the teaching (2x2) model. How shall we proceed?

Could we make a short teaching session via Microsoft Teams or Zoom? I have no hurry, I rely entirely on your time schedule. I would have time on Thursday, 21 Sept 2023.

I wish you a nice weekend.

Best regards,
Fritz

Von: Geoff Shuetrim ***@***.***>
Gesendet: Freitag, 15. September 2023 09:46
An: McKibbin-Software-Group/issues ***@***.***>
Cc: Breuss, Fritz ***@***.***>; Author ***@***.***>
Betreff: Re: [McKibbin-Software-Group/issues] G-Cubed Python (Issue #9)


Hi Fritz,

My apologies for the slow response. Your questions led me to think you were doing the masters course at the Crawford School taught by Warwick McKibbin. If you are not doing that course, I would be happy to assist you with exploring how to use the teaching model to do various simulations.

If you want access to the full model, then you should reach out to Warwick at McKibbin Software Group. Warwick can be reached at ***@***.******@***.***>. More details are available at https://www.sensiblepolicy.com/

Regards

Geoff Shuetrim

**Comment by shuetrim** [comment]
I am not available though next week. Perhaps we can move plans for a catch-up to the following week. Email me at geoff.shuetrim@gmail.com.

To get started though, try running the example scripts that are in the model's main directory. If you have managed to get those examples running, by working through the guidance on the documentation site, then you are well on your way. Some simulations are very straightforward - pick the exogenous variables to adjust and the year to begin adjustments (the event year), set up an experiment folder of your own with an appropriate experiment design file (design.csv) and a suitable simulation layer file (another CSV file referred to by the design file) and then make adjustments to the python program to run your own experiment.

More complex things can be done but if you are across that simpler use case we can make good progress when we talk.

Regards

Geoff

**Comment by breussf** [comment]
Dear Geoff,

thank you.

Best regards,
Fritz

Von: Geoff Shuetrim ***@***.***>
Gesendet: Freitag, 15. September 2023 23:41
An: McKibbin-Software-Group/issues ***@***.***>
Cc: Breuss, Fritz ***@***.***>; Author ***@***.***>
Betreff: Re: [McKibbin-Software-Group/issues] G-Cubed Python (Issue #9)


I am not available though next week. Perhaps we can move plans for a catch-up to the following week. Email me at ***@***.******@***.***>.

To get started though, try running the example scripts that are in the model's main directory. If you have managed to get those examples running, by working through the guidance on the documentation site, then you are well on your way. Some simulations are very straightforward - pick the exogenous variables to adjust and the year to begin adjustments (the event year), set up an experiment folder of your own with an appropriate experiment design file (design.csv) and a suitable simulation layer file (another CSV file referred to by the design file) and then make adjustments to the python program to run your own experiment.

More complex things can be done but if you are across that simpler use case we can make good progress when we talk.

Regards

Geoff

**Comment by shuetrim** [comment]
I am available this week if you want to have a zoom session to discuss model usage.

Regards

Geoff

**Comment by breussf** [comment]
Dear Geoff,

thank you for your info. Well, this week I am not available. Maybe next week.

Which time would fit for you for a zoom session (Australian time is 8 hours ahead of Vienna time)?

Best regards,
Fritz

Von: Geoff Shuetrim ***@***.***>
Gesendet: Montag, 25. September 2023 00:09
An: McKibbin-Software-Group/issues ***@***.***>
Cc: Breuss, Fritz ***@***.***>; Author ***@***.***>
Betreff: Re: [McKibbin-Software-Group/issues] G-Cubed Python (Issue #9)


I am available this week if you want to have a zoom session to discuss model usage.

Regards

Geoff
